language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules
  yarn: true

# S: Build Lifecycle
install:
  - yarn

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      script:
        - cd packages/better-ui
        - yarn test
branches:
  only:
    - master
